# These values should match what is in svreal.sv

DEF_LONG_WIDTH_REAL = 25
DEF_SHORT_WIDTH_REAL = 18
DEF_HARD_FLOAT_EXP_WIDTH = 8
DEF_HARD_FLOAT_SIG_WIDTH = 23
DEF_HARD_FLOAT_WIDTH = 1 + DEF_HARD_FLOAT_EXP_WIDTH + DEF_HARD_FLOAT_SIG_WIDTH
